# Generated by Django 6.0.3 on 2026-05-03 13:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+359888000000', help_text='Enter phone number with country code for contact purposes', max_length=128, region=None),
            preserve_default=False,
        ),
    ]
