# Generated by Django 6.0.3 on 2026-05-03 13:04

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_businesshours_bookingrequest_is_paid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingrequest',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Enter phone number with country code for contact purposes', max_length=128, region=None),
        ),
    ]
