# Generated by Django 6.0.3 on 2026-05-03 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0008_alter_bookingrequest_phone'),
        ('productions', '0006_alter_category_cover_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepackage',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages', to='productions.category'),
        ),
    ]
